# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: It's alex's blog
author: Alex Miller
email: alex@alex-miller.co
description: > # this means to ignore newlines until "baseurl:"
  This is Alex's blog.  It probably contains topics on stuff like Ruby on Rails,
  AngularJS, Elixir, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.alex-miller.co"
twitter_username: apmiller108
github_username:  apmiller108
linkedin: https://www.linkedin.com/in/alex-miller-551b0b59
website: "http://www.alex-miller.co"
disqus: 
  shortname: "blog-alex-miller"
til: "https://alex-til.herokuapp.com"
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude: [vendor/bundle, Gemfile, Gemfile.lock]
